drivers: nfc: Import ASUS changes from 31.1004.0404.107
drivers/nfc/pn8xt/nfc/pn8xt.c:124:42: error: too many arguments to function call, expected 1, have 3
        sigret = force_sig_info(SIG_NFC, &sinfo, task);
                 ~~~~~~~~~~~~~~          ^~~~~~~~~~~~
include/linux/sched/signal.h:329:12: note: 'force_sig_info' declared here
extern int force_sig_info(struct kernel_siginfo *);
           ^
drivers/nfc/pn8xt/nfc/pn8xt.c:512:32: warning: implicit conversion from enumeration type 'enum pn8xt_jcop_dwnld_state' to different enumeration type 'pn8xt_access_st_t' (aka 'enum pn8xt_access_state') [-Wenum-convers>                signal_handler(JCP_DN_INIT, pn8xt_dev->service_pid);
                ~~~~~~~~~~~~~~ ^~~~~~~~~~~
drivers/nfc/pn8xt/nfc/pn8xt.c:529:28: warning: implicit conversion from enumeration type 'enum pn8xt_jcop_dwnld_state' to different enumeration type 'pn8xt_access_st_t' (aka 'enum pn8xt_access_state') [-Wenum-convers>            signal_handler(JCP_DWP_DN_COMP, pn8xt_dev->service_pid);
            ~~~~~~~~~~~~~~ ^~~~~~~~~~~~~~~
2 warnings and 1 error generated.

Change-Id: I7ca43f08130177a98b996cf097772b4e84c1dd03